# Generated by Django 2.0.1 on 2018-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concussiontest', '0002_athlete_base_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='new_time_1',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='new_time_2',
        ),
    ]
